"""Shared OOXML helpers: namespace maps, XML parsing, and small utilities.

This module centralises everything related to the raw OOXML (OpenXML) format
used inside a .pptx package. A .pptx file is really a ZIP archive containing
many XML "parts". We parse those parts with lxml and manipulate the DrawingML
text nodes directly so that every other byte of the package is preserved.
"""

from __future__ import annotations

import hashlib
import re

from lxml import etree

# ---------------------------------------------------------------------------
# Namespaces
# ---------------------------------------------------------------------------
# DrawingML (text), PresentationML (slides/shapes), and relationships.
NS = {
    "a": "http://schemas.openxmlformats.org/drawingml/2006/main",
    "p": "http://schemas.openxmlformats.org/presentationml/2006/main",
    "r": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
    "ct": "http://schemas.openxmlformats.org/package/2006/content-types",
    "rel": "http://schemas.openxmlformats.org/package/2006/relationships",
}


def q(prefix: str, tag: str) -> str:
    """Build a Clark-notation qualified name, e.g. q('a', 'p') -> '{..}p'."""
    return "{%s}%s" % (NS[prefix], tag)


# Commonly used qualified names.
A_P = q("a", "p")        # <a:p>   paragraph
A_R = q("a", "r")        # <a:r>   run
A_T = q("a", "t")        # <a:t>   text
A_BR = q("a", "br")      # <a:br>  line break
A_FLD = q("a", "fld")    # <a:fld> field (e.g. slide number)
A_RPR = q("a", "rPr")    # <a:rPr> run properties


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------
# A parser that keeps the document faithful (no pretty-printing / stripping).
_PARSER = etree.XMLParser(
    remove_blank_text=False,
    remove_comments=False,
    remove_pis=False,
    resolve_entities=False,
    strip_cdata=False,
)


def parse_xml(data: bytes) -> etree._Element:
    """Parse raw XML bytes into an lxml element tree root."""
    return etree.fromstring(data, parser=_PARSER)


def serialize_xml(root: etree._Element, original: bytes | None = None) -> bytes:
    """Serialise an element back to bytes, preserving the XML declaration.

    We try to reproduce the original declaration (encoding / standalone) so the
    patched part stays as close to the original as possible.
    """
    xml_declaration = True
    standalone = None
    encoding = "UTF-8"

    if original is not None:
        head = original[:200].decode("utf-8", errors="replace")
        m = re.match(r"\s*<\?xml[^>]*\?>", head)
        if m:
            decl = m.group(0)
            enc_m = re.search(r'encoding=["\']([^"\']+)["\']', decl)
            if enc_m:
                encoding = enc_m.group(1)
            sa_m = re.search(r'standalone=["\']([^"\']+)["\']', decl)
            if sa_m:
                standalone = sa_m.group(1).lower() == "yes"
        else:
            xml_declaration = False

    return etree.tostring(
        root,
        xml_declaration=xml_declaration,
        encoding=encoding,
        standalone=standalone,
    )


# ---------------------------------------------------------------------------
# Text helpers
# ---------------------------------------------------------------------------
def paragraph_runs(paragraph: etree._Element) -> list[etree._Element]:
    """Return the <a:r> run children of a paragraph, in document order."""
    return [child for child in paragraph if child.tag == A_R]


def run_text(run: etree._Element) -> str:
    """Return the text content of a single run (<a:r>)."""
    t = run.find(A_T)
    if t is None or t.text is None:
        return ""
    return t.text


def paragraph_text(paragraph: etree._Element) -> str:
    """Join the editable run text in a paragraph, turning <a:br> into newlines.

    This is the "source" text a translator sees for one paragraph. Line breaks
    are represented as ``\n`` so the full logical line is kept together.

    Auto-generated fields (<a:fld>: slide numbers, dates) are intentionally
    excluded: their text is regenerated by PowerPoint and they are never patched,
    so including them would create untranslatable, unstable units.
    """
    parts: list[str] = []
    for child in paragraph:
        if child.tag == A_R:
            parts.append(run_text(child))
        elif child.tag == A_BR:
            parts.append("\n")
    return "".join(parts)


def sha256_text(text: str) -> str:
    """Stable SHA-256 hex digest of the given text (UTF-8)."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sanitize_id_fragment(value: str) -> str:
    """Make a string safe to use inside a stable unit id."""
    return re.sub(r"[^A-Za-z0-9]+", "-", value).strip("-").lower()
